from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from states.structured_context import StructuredContext
from states.test_case_state import TestCaseRow



# -----------------------------
# Jira Story (Input Intent)
# -----------------------------

class JiraStory(BaseModel):
    key: str = Field(..., description="Jira issue key, e.g., AIR-102")
    labels: List[str] = Field(default_factory=list, description="Jira labels used as domain signals")
    description: str = Field(..., description="Full Jira description including acceptance criteria")
    summary: str = Field(..., example="Flight booking should work")
    priority: Optional[str] = Field(None, description="Priority of the Jira story")


# -----------------------------
# Retrieved Knowledge Chunk
# -----------------------------

class RetrievedChunk(BaseModel):
    chunk_id: str = Field(..., description="Unique identifier of the chunk in Pinecone")
    text: str = Field(..., description="Chunk content")
    source: str = Field(..., description="Source system, e.g., jira, confluence, mongodb, logs")
    namespace: str = Field(..., description="Pinecone namespace")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")

# -----------------------------
# LangGraph Agent State
# -----------------------------

class AgentState(BaseModel):
    # Input
    jira_story: JiraStory

    # Tool Output
    retrieved_chunks: List[RetrievedChunk] = Field(
        default_factory=list,
        description="Chunks retrieved from Pinecone via tool; authoritative knowledge"
    )

    # Agent 1 Output
    structured_context: Optional[StructuredContext] = Field(
        None,
        description="Final structured context produced by the agent"
    )

    
    test_cases: Optional[TestCaseRow] = Field(None, description="Test Cases generated by agent")
    
    # Execution Metadata (optional but useful)
    errors: Optional[str] = Field(
        None,
        description="Error message if the agent fails to produce valid output"
    )


class GenerateContextRequest(BaseModel):
    jira_story: JiraStory


class GenerateTestCasesRequest(BaseModel):
    jira_story: JiraStory
    structured_context: StructuredContext